services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "443:5678"  # Map HTTPS to n8n internal port
    environment:
      - N8N_HOST=automation.jypi.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_SSL_KEY=/etc/n8n-certs/privkey.pem
      - N8N_SSL_CERT=/etc/n8n-certs/fullchain.pem

      - N8N_SECURE_COOKIE=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - /etc/letsencrypt/live/automation.jypi.org:/etc/n8n-certs:ro
      - /etc/letsencrypt/archive/automation.jypi.org:/etc/letsencrypt/archive/automation.jypi.org:ro

    restart: unless-stopped
    depends_on:
      - scraper

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./scraper:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  n8n_data: